---
- include_role:
    name: common/install_dependencies

- include_role:
    name: common/clone_repo
  become: true
  become_user: "{{ custom_user }}"

- include_tasks: copy_wsgi_file.yml

# The Datastore original setup did not use a virtualenv and so this role has its own pip install to reflect that
# We recommend using the common/pip_install where possible as using a virtualenv is Python best practice
- include_role:
    name: datastore/pip_install

- include_tasks: setup_datastore.yml
  become: true
  become_user: "{{ custom_user }}"

- include_role:
    name: common/restart_server

- include_role:
    name: common/apache2/apache2_install

- include_role:
    name: common/apache2/apache2_restart

- include_tasks: update_crawler.yml
  become: true
  become_user: "{{ custom_user }}"

- include_role:
    name: common/postgres/postgres_backup_cron
