---
- name: Create backup shell script from template
  template: 
     src: postgres_backup.sh.j2 
     dest: "/usr/local/bin/postgres_backup.sh"
     mode: 0774
     owner: {{ db_user }}
     group: www-data
     
- name: Set the backup shell script to run as a cronjob
  cron:
    become: true
    become_user: {{ db_user }}
    name: "Database backup"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    job: "/usr/local/bin/postgres_backup.sh"
    