---
- name: Create backup directory to hold uncompressed files prior to zipping
  file:
    path: "{{ backup_directory }}"
    state: directory
    owner: "{{ db_user }}"
    group: www-data
    mode: 0775

- name: Create backup shell script from template
  template: 
     src: postgres_backup.sh.j2 
     dest: "/usr/local/bin/postgres_backup.sh"
     mode: 0775
     owner: "{{ db_user }}"
     group: www-data
     
- name: Set the backup shell script to run as a cronjob
  cron:
    user: "{{ db_user }}"
    name: "Database backup"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    weekday: "{{ backup_weekday }}"
    job: "/usr/local/bin/postgres_backup.sh"
    