---
- name: Make db_user a member of the www-data group to allow for reading and writing of media folder
  command: usermod -a -G www-data {{ db_user }}

- name: Create backup directory to hold uncompressed files prior to zipping
  file:
    path: "{{ backup_temporary_location }}{{ backup_directory }}"
    state: directory
    owner: "{{ db_user }}"
    group: "{{ db_user }}"
    mode: 0774

- name: Create backup shell script from template
  template:
     src: postgres_backup.sh.j2
     dest: "/usr/local/bin/postgres_backup.sh"
     mode: 0775

- name: Set the backup shell script to run as a cronjob
  cron:
    name: "Database backup"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    weekday: "{{ backup_weekday }}"
    job: "/usr/local/bin/postgres_backup.sh"
