---
- hosts: datastore-dev
  remote_user: root
  gather_facts: no
  roles:
    - python2
    - postgres
    - datastore

  environment:
    DATABASE_URL: postgres:///iati-datastore

  vars:
    custom_user: datastore
    custom_database: iati-datastore
