---
- name: Install apache2 dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
     - apache2
     - libapache2-mod-wsgi

- name: Enable mod_headers
  apache2_module:
    name: headers
    state: present

- name: Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present

- name: Copy apache2 config file to sites-available
  copy:
    remote_src: no
    src: apache2.conf
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache
