---
- name: Restart server
  become: yes
  shell: sleep 2 && reboot
  async: 1
  poll: 0

- name: Wait for server to come back
  local_action: wait_for host="{{ inventory_hostname }}" port=22 delay=20 connect_timeout=200
