---
- name: Set up cron job to create backup of media folder
  cron:
    name: "Media backup"
    minute: "0"
    hour: "1"
    job: "cp -r {{ django_dir }}/media {{ backup_directory }}/media"
    
- name: Set up cron job to zip media and pg backup
  cron:
    name: "Zip backup"
    minute: "0"
    hour: "2"
    job: "zip --password {{ backup_encryption_key }} -r {{ backup_temporary_location }}/$(date +\%Y-\%m-\%d).zip {{ backup_directory }}"