---
- debug:
    msg: "{{ django_dir }}"

- django_manage:
    command: migrate
    app_path: "{{ django_dir }}"
    virtualenv: "{{ virtualenv_path }}"

- django_manage:
    command: "createsuperuser --noinput --username=admin --email=admin@example.com"
    app_path: "{{ django_dir }}"
    virtualenv: "{{ virtualenv_path }}"
