---
- include_role:
    name: common/clone_repo
  become: true
  become_user: "{{ custom_user }}"

- include_tasks: setup_local_settings.yml

- include_role:
    name: wagtail/pip_install

- include_tasks: django_postgres_setup.yml
  become: true
  become_user: postgres

- include_tasks: django_setup.yml

- include_tasks: change_file_permissions.yml

- include_role:
    name: common/apache2
