- name: Generate a self signed OpenSSL certificate
  openssl_certificate:
    path: "{{ ssl_cert_path }}"
    privatekey_path: "{{ ssl_key_path }}"
    csr_path: "{{ ssl_sign_request_path }}"
    provider: selfsigned
