---
- name: Set authorized keys
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.public_key }}"
    state: present
    exclusive: False
  with_items:
    - authorized_keys

- name: Set authorized external keys
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.public_key }}"
    state: present
    exclusive: False
  with_items:
    - authorized_keys_external
  when: external_dev_servers

- name: Remove unauthorised keys from file
  authorized_key:
    key: "{{ lookup('file' item) }}"
    state: absent
    user: root
  with_items:
    - unauthorised_keys
