---
- name: Set authorized keys
  authorized_key:
    user: root
    key: "{{ item.public_key }}"
    state: present
    exclusive: False
  with_items:
    - "{{ authorized_keys }}"

- name: Set authorized external keys
  authorized_key:
    user: root
    key: "{{ item.public_key }}"
    state: present
    exclusive: False
  with_items:
    - "{{ authorized_keys_external }}"
  when: external_dev_servers is defined

- name: Remove unauthorised keys
  authorized_key:
    user: root
    key: "{{ item.public_key }}"
    state: absent
  with_items:
    - "{{ unauthorised_keys }}"
  when: unauthorised_keys.0 is defined
  