---
required_packages:
  - git
  - libevent-dev
  - libpq-dev
  - libxml2-dev
  - libxslt-dev
  - redis-server

git_clone_address: https://github.com/IATI/IATI-Datastore.git

user_home_dir: /home/{{ custom_user }}/

repo_dir: IATI-Datastore/

wsgi_file_name: datastore.wsgi

apache2_conf_file: apache2.conf

apache2_mod_wsgi_version: libapache2-mod-wsgi

apache2_ip: *

apache2_port: 80

apache2_directories:
  - root: /
  - options:
    - line: Options FollowSymLinks
    
apache2_extras:
  - line: LogLevel info
  - line: WSGIDaemonProcess datastore user=datastore group=datastore processes=1 threads=15
  - line: WSGIProcessGroup datastore
  - line: WSGIScriptAlias / /home/datastore/datastore.wsgi
  - line: Header set Access-Control-Allow-Origin "*"
