---
# Loop through list of packages in required_packages variable and install with apt-get
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
     "{{ required_packages }}"
