---
# python-minimal can't be installed with apt_module as it requires python2 to run
- name: Install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- include_role:
    name: common/install_dependencies
