---
packages:
  - git
  - libevent-dev
  - libpq-dev
  - libxml2-dev
  - libxslt-dev
  - redis-server

github_repo: https://github.com/IATI/IATI-Datastore.git

user_home_dir: /home/{{ custom_user }}/

repo_dir: IATI-Datastore/

wsgi_file_name_name: datastore.wsgi

requirements_file: requirements_dev.txt
