---
# currently residing in datastore rather than common as only needed by datastore. Can be extracted at a later date if necessary.
- include_role:
    name: common/install_dependencies

- name: Enable apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ apache2_modules }}"

- name: Copy apache2 config file to sites-available
  copy:
    remote_src: no
    src: "{{ apache2_conf_template }}"
    dest: "{{ apache2_conf_destination }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
