---
# Note: This is only required because version 2.x is compatible with python3 and is not available via apt
# Be sure to remove this and just install it via install_dependencies when it becomes available    
- name: Install latest version of s3cmd
  pip:
    name: "s3cmd"
    version: 2.0.1
    
- name: Create s3 config file from template
  template: 
     src: s3cfg.j2 
     dest: "/home/{{ custom_user }}/.s3cfg"
     mode: 0644
     owner: "{{ custom_user }}"
     group: www-data
     
- name: Create a new bucket for s3
  become: true
  become_user: "{{ custom_user }}"
  command: s3cmd mb s3://{{ s3_bucket_name }}